//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformeMedConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InformeMedConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow {
            get {
                object obj = ResourceManager.GetObject("Arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Clear {
            get {
                object obj = ResourceManager.GetObject("Clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIOQUÍMICA.
        /// </summary>
        internal static string ParameterTypeDescription_BIOQUIMICA {
            get {
                return ResourceManager.GetString("ParameterTypeDescription_BIOQUIMICA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEMATOLOGIA.
        /// </summary>
        internal static string ParameterTypeDescription_HEMATOLOGIA {
            get {
                return ResourceManager.GetString("ParameterTypeDescription_HEMATOLOGIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MARCADORES TEMPORALES.
        /// </summary>
        internal static string ParameterTypeDescription_MARCADORESTEMPORALES {
            get {
                return ResourceManager.GetString("ParameterTypeDescription_MARCADORESTEMPORALES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTROS.
        /// </summary>
        internal static string ParameterTypeDescription_OTROS {
            get {
                return ResourceManager.GetString("ParameterTypeDescription_OTROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEDIMENTO ORINA.
        /// </summary>
        internal static string ParameterTypeDescription_SEDIMENTOORINA {
            get {
                return ResourceManager.GetString("ParameterTypeDescription_SEDIMENTOORINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIRA REACTIVA ORINA.
        /// </summary>
        internal static string ParameterTypeDescription_TIRAREACTIVAORINA {
            get {
                return ResourceManager.GetString("ParameterTypeDescription_TIRAREACTIVAORINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URGENCIAS.
        /// </summary>
        internal static string ParameterTypeDescription_URGENCIAS {
            get {
                return ResourceManager.GetString("ParameterTypeDescription_URGENCIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Añadir parámetro.
        /// </summary>
        internal static string ToolTip_AddParameter {
            get {
                return ResourceManager.GetString("ToolTip_AddParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar entradas.
        /// </summary>
        internal static string ToolTip_CleanInputs {
            get {
                return ResourceManager.GetString("ToolTip_CleanInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertir a texto.
        /// </summary>
        internal static string ToolTip_ConvertText {
            get {
                return ResourceManager.GetString("ToolTip_ConvertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar al clipboard.
        /// </summary>
        internal static string ToolTip_CopyToClipboard {
            get {
                return ResourceManager.GetString("ToolTip_CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrar texto.
        /// </summary>
        internal static string ToolTip_DeleteText {
            get {
                return ResourceManager.GetString("ToolTip_DeleteText", resourceCulture);
            }
        }
    }
}
